//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer()
        {
            this.VocabularyResults = new HashSet<VocabularyResult>();
        }
    
        public System.Guid Id { get; set; }
        public string Details { get; set; }
        public Nullable<System.Guid> KeyId { get; set; }
        public Nullable<System.Guid> QuestionId { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> WordId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<bool> IsTrue { get; set; }
        public string DetailsVi { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.Guid> ImgMediaId { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VocabularyResult> VocabularyResults { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Question Question { get; set; }
        public virtual Word Word { get; set; }
    }
}
