//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversationSentence
    {
        public System.Guid Id { get; set; }
        public string NameVi { get; set; }
        public string NameDe { get; set; }
        public Nullable<System.Guid> ConversationId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> Location { get; set; }
    
        public virtual Conversation Conversation { get; set; }
    }
}
