//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.VocabularyResults = new HashSet<VocabularyResult>();
            this.Answers = new HashSet<Answer>();
        }
    
        public System.Guid Id { get; set; }
        public string NameDe { get; set; }
        public string NameVi { get; set; }
        public string DetailDe { get; set; }
        public string DetailVi { get; set; }
        public Nullable<System.Guid> WordId { get; set; }
        public Nullable<System.Guid> MediaId { get; set; }
        public Nullable<System.Guid> QuestionTypeId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> FormatAnswer { get; set; }
        public Nullable<System.Guid> FormatQuestion { get; set; }
        public Nullable<System.Guid> Grammar_TheoryId { get; set; }
        public Nullable<System.Guid> ImgMediaId { get; set; }
        public Nullable<System.Guid> CommunicationId { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VocabularyResult> VocabularyResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Grammar_Theory Grammar_Theory { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Medium Medium1 { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual Word Word { get; set; }
    }
}
