//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public System.Guid Id { get; set; }
        public string NoteVi { get; set; }
        public string NoteDe { get; set; }
        public System.Guid SubjectId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Index { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
