//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThiAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThiAnswer()
        {
            this.ThiResults = new HashSet<ThiResult>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<int> Index { get; set; }
        public string AnswerVi { get; set; }
        public string AnswerDe { get; set; }
        public System.Guid QuestionID { get; set; }
        public Nullable<bool> IsTrue { get; set; }
        public Nullable<System.Guid> AudioMediaId { get; set; }
        public Nullable<System.Guid> ImageMediaId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual Medium Medium { get; set; }
        public virtual Medium Medium1 { get; set; }
        public virtual ThiQuestion ThiQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiResult> ThiResults { get; set; }
    }
}
