//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThiBaiTapThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThiBaiTapThi()
        {
            this.ThiQuestions = new HashSet<ThiQuestion>();
        }
    
        public System.Guid ID { get; set; }
        public string BtNameVi { get; set; }
        public string BtNameDe { get; set; }
        public Nullable<System.Guid> DeThiID { get; set; }
        public Nullable<System.Guid> SubjectTypeId { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string NoteVi { get; set; }
        public string NoteDe { get; set; }
    
        public virtual ThiDeThi ThiDeThi { get; set; }
        public virtual ThiTypeSubject ThiTypeSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiQuestion> ThiQuestions { get; set; }
    }
}
