//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThiQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThiQuestion()
        {
            this.ThiAnswers = new HashSet<ThiAnswer>();
            this.ThiResults = new HashSet<ThiResult>();
        }
    
        public System.Guid ID { get; set; }
        public string QuestionVi { get; set; }
        public string QuestionDe { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.Guid QuestionTypeID { get; set; }
        public Nullable<long> LimitedTime { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<System.Guid> AudioMediaId { get; set; }
        public Nullable<System.Guid> ImageMediaId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.Guid> BaiTapThiID { get; set; }
    
        public virtual Medium Medium { get; set; }
        public virtual Medium Medium1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiAnswer> ThiAnswers { get; set; }
        public virtual ThiBaiTapThi ThiBaiTapThi { get; set; }
        public virtual ThiQuestionType ThiQuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiResult> ThiResults { get; set; }
        public object DeThiID { get; set; }
    }
}
