//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThiResult
    {
        public System.Guid ID { get; set; }
        public System.Guid StudentID { get; set; }
        public System.Guid QuestionID { get; set; }
        public System.Guid AnswerID { get; set; }
        public Nullable<System.Guid> DeThiID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsTrue { get; set; }
        public string AnswerContent { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ThiAnswer ThiAnswer { get; set; }
        public virtual ThiDeThi ThiDeThi { get; set; }
        public virtual ThiQuestion ThiQuestion { get; set; }
    }
}
