//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThiTypeSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThiTypeSubject()
        {
            this.ThiBaiTapThis = new HashSet<ThiBaiTapThi>();
        }
    
        public System.Guid ID { get; set; }
        public string TypeNameVi { get; set; }
        public string TypeNameDe { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Icon { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<int> Index { get; set; }
        public string NoteVi { get; set; }
        public string NoteDe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiBaiTapThi> ThiBaiTapThis { get; set; }
    }
}
