//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_DB_ELEANING.AFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VocabularyResult
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> QuestionId { get; set; }
        public Nullable<System.Guid> AnswerId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> StudenId { get; set; }
        public string StudentWord { get; set; }
        public Nullable<System.Guid> WordAnswerId { get; set; }
        public Nullable<System.Guid> ImageAnswerId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
    }
}
